### ISSUE TITLE
nginx.conf文件配置

### ISSUE THREAD

**Issue by liresky** [wisdom-projects/holer#24]
如果使用系统自动安装的nginx，nginx配置就没法使用。

**Comment by WisdomFamily** [comment]
下载最新的[holer-server.zip](https://sourceforge.net/projects/holer/files/v1.2/)软件包
```
  nginx:
     bin: /usr/sbin       ==>这里是nginx可执行程序所在的目录
     conf: /etc/nginx   ==>这里是nginx.conf文件所在的目录
    #home: /usr/local/nginx  ==> 如果设置bin 和 conf，无需设置home，即使设置了home目录也会被忽略掉
```

**注意事项：**
1. 如果Linux系统安装的Nginx目录结构如下：
```
Nginx主目录
├── conf
│   ├── nginx.conf
├── bin
│   ├── nginx
.   .
.   .
```
只需要设置home即可

```
  nginx:
     home: Nginx主目录
```
2. 如果系统安装的Nginx目录结构如下：
```
/usr/sbin/nginx
/etc/nginx/nginx.conf

```
无需设置home目录，需要设置bin和conf如下：
```
  nginx:
     bin: /usr/sbin  
     conf: /etc/nginx
```
